# capability_cic.py -- P2 of the journal extension: adversarial-training baseline.
#
# The paper shows that architecture alone confers little robustness, and that the
# realizable threat (L2) is far smaller than the unconstrained one (L0). The open
# question a reviewer will ask is what a defender should actually do. This trains
# PGD adversarially-trained detectors and evaluates them at BOTH capability levels,
# so the defence can be judged against the threat that actually exists rather than
# the inflated one.
#
# Reports, for each activation and seed:
#   clean test macro-F1        (the cost of the defence)
#   worst-case ASR at L0       (benefit against the unconstrained threat)
#   worst-case ASR at L2       (benefit against the realizable threat)
# for both a standard and an adversarially-trained model, so all four cells of the
# defence x threat-model comparison are populated.
#
# Reuses the attack helpers and the constraint schema from attack1_cic.py so that
# the defence is evaluated with exactly the same attacks, masks and ASR definition.
#
# Usage, beside nids_cic.py:
#     python capability_cic.py
# Output: results_advtrain_cic.csv
#   columns: defence, level, depth, activation, features, seed, eps, worst_asr, clean_f1
#
# Cost: roughly 8x a clean run (7 inner PGD steps on half of every batch).
import os, time
import numpy as np, pandas as pd, torch
from sklearn.model_selection import train_test_split
import re


# ---- constraint schema (inlined from constraints.py: no separate file needed)
# --------------------------------------------------------------- UNSW-NB15
# one-hot expansions and binary indicators
UNSW_CATEGORICAL = (
    r"^(proto|service|state)_",     # one-hot groups
    r"^is_sm_ips_ports$",           # binary: src/dst IP+port equal
    r"^is_ftp_login$",
)
# statistics generated by the DESTINATION host; an adversary shaping its own
# traffic cannot set these directly
UNSW_DEST_SIDE = (
    r"^d(bytes|pkts|load|loss|mean|ttl|tcpb|win|jit|inpkt)$",
    r"^res_bdy_len$",
    r"^dur$",                       # negotiated jointly; treated as not directly settable
)
# connection-tracking aggregates over a recent window: influenced only by
# sustained behaviour, never per-flow
UNSW_CT_AGG = (r"^ct_",)

# ------------------------------------------------------------ CSE-CIC-IDS2018
CIC_CATEGORICAL = (
    r"Flag Count$", r"Flags$",      # SYN/FIN/RST/PSH/ACK/URG counts and flag fields
    r"^Protocol$",
)
CIC_DEST_SIDE = (
    r"^Bwd ",                       # backward = victim -> attacker
    r"^Init Bwd Win Bytes$",
)
# flow-level aggregates are deterministic functions of the fwd+bwd streams;
# perturbing them independently is inconsistent
CIC_DERIVED = (
    r"^Flow ", r"^Idle ", r"^Active ", r"^Packet Length ", r"^Average Packet Size$",
    r"^Down/Up Ratio$",
)


def _any(patterns, name):
    return any(re.search(p, name) for p in patterns)


def classify(feature_names, dataset):
    # Return dict name -> 'categorical' | 'dest' | 'derived' | 'free'.
    ds = dataset.lower()
    out = {}
    for n in feature_names:
        n = str(n)
        if ds == "unsw":
            if _any(UNSW_CATEGORICAL, n):  out[n] = "categorical"
            elif _any(UNSW_DEST_SIDE, n):  out[n] = "dest"
            elif _any(UNSW_CT_AGG, n):     out[n] = "derived"
            else:                          out[n] = "free"
        else:
            if _any(CIC_CATEGORICAL, n):   out[n] = "categorical"
            elif _any(CIC_DEST_SIDE, n):   out[n] = "dest"
            elif _any(CIC_DERIVED, n):     out[n] = "derived"
            else:                          out[n] = "free"
    return out


def build_mask(feature_names, dataset, level):
    # Binary mask, shape (n_features,), 1 = perturbable.
    #     level: 0 unconstrained | 1 one-hot integrity | 2 realizable
    if level == 0:
        return np.ones(len(feature_names), dtype=np.float32)
    cls = classify(feature_names, dataset)
    frozen = {"categorical"} if level == 1 else {"categorical", "dest", "derived"}
    return np.array([0.0 if cls[str(n)] in frozen else 1.0
                     for n in feature_names], dtype=np.float32)


def summarise(feature_names, dataset):
    # Print the schema -- paste into the paper as the capability table.
    cls = classify(feature_names, dataset)
    order = ["categorical", "dest", "derived", "free"]
    label = {"categorical": "Categorical / one-hot / flag (frozen at L1, L2)",
             "dest":        "Destination-side statistic  (frozen at L2)",
             "derived":     "Derived / aggregate         (frozen at L2)",
             "free":        "Adversary-controllable      (always perturbable)"}
    print(f"--- {dataset.upper()}: {len(feature_names)} features ---")
    for k in order:
        members = [n for n in feature_names if cls[str(n)] == k]
        print(f"  {label[k]}: {len(members)}")
        for m in members:
            print(f"      {m}")
    for lv in (0, 1, 2):
        m = build_mask(feature_names, dataset, lv)
        print(f"  L{lv}: {int(m.sum())}/{len(m)} features perturbable "
              f"({100*m.mean():.0f}%)")


def load_feature_names(G, dataset, order, k):
    # Column names for the selected top-k features, from the grid module G.
    import os, glob
    import numpy as _np
    if dataset.lower() == "unsw":
        d = _np.load(G.NPZ_UNSW, allow_pickle=True)
        if "feature_names" not in d:
            raise SystemExit("unsw_processed.npz has no feature_names; the mask "
                             "cannot be built without column names.")
        names = list(d["feature_names"])
    else:
        import pandas as _pd
        hits = glob.glob(os.path.expanduser(
            "~/.cache/kagglehub/datasets/dhoogla/distrinetcsecicids2018/**/*.parquet"),
            recursive=True)
        if not hits:
            raise SystemExit("CIC parquet cache not found; cannot read column names.")
        cols = [str(x).strip() for x in _pd.read_parquet(sorted(hits)[0]).columns]
        names = [x for x in cols if x.lower() != "label"]
    return [names[i] for i in order[:k]]


DS         = "cic"                # hard-wired: this file is the CIC run
SEEDS_OVERRIDE = None          # None -> the paper's 3 seeds. For the stability
                               # run set [1,7,42,2,13,23,31,57,77,99]; the first
                               # three are the published seeds, so the 3-seed
                               # results stay recoverable from the 10-seed file.
MASK_LEVELS = [0, 1, 2]        # 0 unconstrained | 1 one-hot | 2 realizable
                               # all levels in ONE pass: the target models and the
                               # transfer surrogate are trained once and reused, so
                               # this costs far less than three separate runs.
DEPTH, FEATS = 4, 30
MATCH_PUBLISHED_SPLIT = True   # True  -> random_state=SEED, reproducing the models
                               #          behind results_full_*.csv (comparable)
                               # False -> random_state=seed, per-seed re-randomised
                               #          (honest variance, NOT comparable)
SUBSTITUTE = dict(depth=2, act="tanh", seed_offset=1000)   # deliberately mismatched
ATTACK_TIMEOUT = 1200      # seconds per attack; exceeded -> recorded as timeout, run continues
CW_MAX_SAMPLES = 500       # C&W is O(minutes/sample) in ART; cap its pool and say so

import nids_cic as G
import torch.nn.functional as F
DEVICE, EPS = G.DEVICE, G.EPS_LIST
SEEDS = SEEDS_OVERRIDE or G.SEEDS


def _apply(X, adv, mask):
    # Confine a finished perturbation to the perturbable features.
    #     Used for AutoAttack and C&W, whose ART implementations take no mask
    #     argument. Restricting after the fact can only weaken an attack, so under
    #     MASK_LEVEL > 0 these two are LOWER BOUNDS -- report them as such.
    if mask is None:
        return adv
    return (X + (adv - X) * mask).astype(np.float32)


def _kw(cls, **kw):
    # Keep only the kwargs this ART version's constructor actually accepts.
    #     ART's attack signatures drift between releases (CarliniLInfMethod dropped
    #     `eps`, for instance), so filter rather than assume.
    import inspect
    ok = set(inspect.signature(cls.__init__).parameters)
    return {k: v for k, v in kw.items() if k in ok}


def _ref(clf, X, eps, mask, which):
    # PGD / BIM re-run here as in-script reference points.
    #     The published grid and this script train separate model instances, so the
    #     only airtight comparison between the conference attacks and the new ones is
    #     a within-script one. These two rows provide it.
    from art.attacks.evasion import BasicIterativeMethod, ProjectedGradientDescent
    kw = dict(eps=eps, eps_step=eps / G.FGSM_EPS_STEP_DIV,
              max_iter=G.PGD_BIM_MAX_ITER, batch_size=G.BATCH_SIZE)
    atk = (ProjectedGradientDescent(clf, num_random_init=G.PGD_RANDOM_INIT, **kw)
           if which == "pgd" else BasicIterativeMethod(clf, **kw))
    gk = {} if mask is None else {"mask": np.broadcast_to(
        mask, X.shape).astype(np.float32).copy()}
    return atk.generate(x=X.astype(np.float32), **gk)


def a_spsa(model, X, y, eps, seed, mask):
    # SPSA exactly as in the published grid (G.SPSA_STEPS / G.SPSA_NDIRS / G.SPSA_C,
    # same alpha schedule and eps clipping), with the capability mask applied to the
    # random probe directions so frozen features never move.
    rng = np.random.default_rng(seed)
    x0 = np.ascontiguousarray(X, np.float32); x = x0.copy()
    m = 1.0 if mask is None else mask
    alpha = eps / G.SPSA_STEPS * 2.5
    for _ in range(G.SPSA_STEPS):
        g = np.zeros_like(x)
        for _ in range(G.SPSA_NDIRS):
            d = rng.choice([-1.0, 1.0], size=x.shape).astype(np.float32) * m
            g += ((G._ce(model, x + G.SPSA_C * d, y, DEVICE) -
                   G._ce(model, x - G.SPSA_C * d, y, DEVICE)) / (2 * G.SPSA_C))[:, None] * d
        x = x + alpha * np.sign(g) * m
        x = np.clip(x, x0 - eps, x0 + eps)
    return x.astype(np.float32)


def a_apgd(clf, X, eps, mask):
    # Auto-PGD with cross-entropy loss -- the strongest white-box attack that is
    #     actually applicable here.
    #     AutoAttack as published cannot be run on this problem: two of its four
    #     components do not apply to binary tabular data. APGD with the DLR loss is
    #     defined through the third-largest logit and is undefined for 2 classes
    #     (ART raises `index -3 is out of bounds`), and ART's Square Attack accepts
    #     only image-shaped input (`Attack can only be applied to image data`). What
    #     remains -- and what we report -- is APGD-CE, which is parameter-free apart
    #     from the budget and strictly stronger than plain PGD.
    from art.attacks.evasion import AutoProjectedGradientDescent
    atk = AutoProjectedGradientDescent(**_kw(
        AutoProjectedGradientDescent, estimator=clf, norm=np.inf, eps=eps,
        eps_step=eps / 4.0, max_iter=100, nb_random_init=5,
        loss_type="cross_entropy", targeted=False, batch_size=512, verbose=False))
    return _apply(X, atk.generate(x=X.astype(np.float32)), mask)


def a_deepfool(clf, X, eps, mask):
    # DeepFool -- minimum-norm white-box attack, projected into the eps-ball.
    #     Included as the second member of the strong white-box set, in place of the
    #     AutoAttack components that do not apply. Minimum-norm, so a LOWER BOUND at
    #     a fixed budget.
    from art.attacks.evasion import DeepFool
    atk = DeepFool(**_kw(DeepFool, classifier=clf, estimator=clf, max_iter=100,
                         nb_grads=2, batch_size=512, verbose=False))
    return _apply(X, atk.generate(x=X.astype(np.float32)), mask)


class _Timeout(Exception):
    pass


def _run_with_timeout(fn, seconds):
    # Abort an attack that exceeds its budget instead of hanging the grid.
    import signal
    def _h(signum, frame):
        raise _Timeout()
    old = signal.signal(signal.SIGALRM, _h); signal.alarm(seconds)
    try:
        return fn()
    finally:
        signal.alarm(0); signal.signal(signal.SIGALRM, old)


def a_cw(clf, X, eps, mask):
    # Carlini-Wagner. Falls back across ART signature variants.
    #     Newer ART removed `eps` from CarliniLInfMethod; when the bound is not a
    #     constructor argument the attack is minimum-norm and is projected into the
    #     eps-ball by the caller, which makes it a LOWER BOUND at that budget.
    from art.attacks.evasion import CarliniLInfMethod
    n  = min(CW_MAX_SAMPLES, len(X))     # ART's C&W is far too slow on the full pool
    Xs = X[:n].astype(np.float32)
    adv = CarliniLInfMethod(**_kw(
        CarliniLInfMethod, classifier=clf, estimator=clf, eps=eps, max_iter=10,
        batch_size=512, verbose=False)).generate(x=Xs)
    # return the SUBSET plus its indices, so ASR is computed only over the flows
    # actually attacked -- scoring un-attacked flows would deflate the rate.
    return _apply(Xs, adv, mask), np.arange(n)


def a_hsj_bounded(clf, X, eps, mask):
    # HopSkipJump seeded with an eps-bounded PGD example.
    #     The conference version generated HSJ unbounded and projected afterwards,
    #     which generally lands on a non-adversarial point. Starting inside the ball
    #     and re-projecting after each call keeps the search where it belongs.
    from art.attacks.evasion import HopSkipJump, ProjectedGradientDescent
    pgd = ProjectedGradientDescent(clf, eps=eps, eps_step=eps / G.FGSM_EPS_STEP_DIV,
                                   max_iter=G.PGD_BIM_MAX_ITER,
                                   num_random_init=1, batch_size=G.BATCH_SIZE)
    kw = {} if mask is None else {"mask": np.broadcast_to(
        mask, X.shape).astype(np.float32).copy()}
    init = pgd.generate(x=X.astype(np.float32), **kw)
    atk = HopSkipJump(classifier=clf, targeted=False, max_iter=G.HSJ_MAX_ITER,
                      max_eval=G.HSJ_MAX_EVAL, init_eval=G.HSJ_INIT_EVAL,
                      batch_size=128, verbose=False)
    adv = atk.generate(x=X.astype(np.float32), x_adv_init=init.astype(np.float32))
    adv = np.where(np.isfinite(adv).all(1, keepdims=True), adv, init)
    adv = _apply(X, adv, mask)
    return (X + np.clip(adv - X, -eps, eps)).astype(np.float32)


_SUB_CACHE = {}


def a_transfer(Xtrn, ytrn, Xval, yval, k, X, eps, seed, mask):
    # Train a mismatched surrogate, craft PGD on it, hand the result to the target.
    # the surrogate depends on the seed alone -- not on eps, not on the mask --
    # so train it once per seed instead of once per (eps, level) call
    if seed not in _SUB_CACHE:
        s = seed + SUBSTITUTE["seed_offset"]
        torch.manual_seed(s); np.random.seed(s); torch.cuda.manual_seed_all(s)
        sub = G.build_model(SUBSTITUTE["depth"], k, SUBSTITUTE["act"]).to(DEVICE)
        G.train_to_convergence(sub, Xtrn, ytrn, Xval, yval, DEVICE); sub.eval()
        _SUB_CACHE[seed] = (sub, G._art_clf(sub, Xtrn, DEVICE))
    sub, sub_clf = _SUB_CACHE[seed]
    from art.attacks.evasion import ProjectedGradientDescent
    atk = ProjectedGradientDescent(sub_clf, eps=eps,
                                   eps_step=eps / G.FGSM_EPS_STEP_DIV,
                                   max_iter=G.PGD_BIM_MAX_ITER, num_random_init=1,
                                   batch_size=G.BATCH_SIZE)
    kw = {} if mask is None else {"mask": np.broadcast_to(
        mask, X.shape).astype(np.float32).copy()}
    return atk.generate(x=X.astype(np.float32), **kw)


# ---- adversarial training -------------------------------------------------
AT_EPS      = 0.3      # training budget; matches the mid budget used throughout
AT_STEPS    = 7        # inner PGD steps (Madry-style)
AT_RATIO    = 0.5      # fraction of each batch replaced by adversarial examples
EVAL_LEVELS = [0, 2]   # unconstrained and realizable
EVAL_ATKS   = ["pgd", "bim", "spsa", "transfer"]   # natively maskable only
OUT_AT      = f"results_advtrain_{DS}.csv"


def _pgd_batch(model, X, y, eps, steps, mask):
    # inner PGD used to generate training adversarials; kept in torch so it is
    # fast enough to run every batch. Mask is applied to the gradient sign step,
    # so AT can be run against a constrained threat model too.
    model.eval()
    x0 = X.clone().detach()
    x = x0 + torch.empty_like(x0).uniform_(-eps, eps)
    m = None if mask is None else torch.tensor(mask, device=X.device)
    if m is not None:
        x = x0 + (x - x0) * m
    step = eps / steps * 2.5
    for _ in range(steps):
        x = x.clone().detach().requires_grad_(True)
        loss = F.cross_entropy(model(x), y)
        g, = torch.autograd.grad(loss, x)
        upd = step * g.sign()
        if m is not None:
            upd = upd * m
        x = torch.clamp(x0 + torch.clamp(x + upd - x0, -eps, eps), -1e6, 1e6)
    model.train()
    return x.detach()


def train_adversarial(model, Xtr, ytr, Xval, yval, mask=None):
    # Same convergence protocol as the clean grid (blocks of G.CHUNK epochs,
    # early stopping on validation macro-F1) so the two training regimes are
    # compared under identical stopping rules -- only the batch content differs.
    opt = torch.optim.Adam(model.parameters(), lr=G.LR)
    Xt = torch.tensor(Xtr, dtype=torch.float32)
    yt = torch.tensor(ytr, dtype=torch.long)
    n, best, stale, done = len(Xt), -1.0, 0, 0
    while done < G.MAX_EPOCHS:
        model.train()
        for _ in range(G.CHUNK):
            perm = torch.randperm(n)
            for i in range(0, n, G.BATCH_SIZE):
                idx = perm[i:i + G.BATCH_SIZE]
                xb = Xt[idx].to(DEVICE); yb = yt[idx].to(DEVICE)
                k = int(len(xb) * AT_RATIO)
                if k > 0:
                    xb = torch.cat([_pgd_batch(model, xb[:k], yb[:k], AT_EPS,
                                               AT_STEPS, mask), xb[k:]], 0)
                opt.zero_grad()
                F.cross_entropy(model(xb), yb).backward()
                opt.step()
        done += G.CHUNK
        f1 = G.macro_f1(model, Xval, yval, DEVICE)
        if f1 > best + G.TOL:
            best, stale = f1, 0
        else:
            stale += 1
            if stale >= G.PATIENCE:
                break
    model.eval()
    return best


def worst_case(model, clf, Xtrn, ytrn, Xval, yval, k, Xe, ye, eps, seed, mask):
    # worst case over the four natively-constrained attacks
    best = 0.0
    for name in EVAL_ATKS:
        try:
            if name in ("pgd", "bim"):
                adv = _ref(clf, Xe, eps, mask, name)
            elif name == "spsa":
                adv = a_spsa(model, Xe, ye, eps, seed, mask)
            else:
                adv = a_transfer(Xtrn, ytrn, Xval, yval, k, Xe, eps, seed, mask)
            best = max(best, G._asr(model, adv, Xe, ye, DEVICE, eps=eps))
        except Exception as e:
            print(f"      {name} failed: {type(e).__name__}", flush=True)
    return best


def main():
    Xtr_full, ytr, Xte_full, yte, order = G.load_cic()
    k = min(FEATS, Xtr_full.shape[1]); ok = order[:k]
    names = load_feature_names(G, DS, order, k)
    masks = {0: None, 2: build_mask(names, DS, 2)}
    print(f"L0: {k}/{k} perturbable   L2: {int(masks[2].sum())}/{k} perturbable")

    rng = np.random.default_rng(G.SEED)
    pool = rng.choice(np.where(yte != 0)[0],
                      size=min(G.N_EVAL, int((yte != 0).sum())), replace=False)
    Xe, ye = Xte_full[pool][:, ok], yte[pool]
    Xtr, Xte = Xtr_full[:, ok], Xte_full[:, ok]
    if os.path.exists(OUT_AT):
        os.remove(OUT_AT)

    rows, t0 = [], time.time()
    for act in G.ACTIVATIONS:
        for seed in SEEDS:
            torch.manual_seed(seed); np.random.seed(seed)
            torch.cuda.manual_seed_all(seed)
            Xtrn, Xval, ytrn, yval = train_test_split(
                Xtr, ytr, test_size=0.1,
                random_state=(G.SEED if MATCH_PUBLISHED_SPLIT else seed),
                stratify=ytr)

            for defence in ("standard", "pgd_at"):
                torch.manual_seed(seed); np.random.seed(seed)
                torch.cuda.manual_seed_all(seed)
                model = G.build_model(DEPTH, k, act).to(DEVICE)
                if defence == "standard":
                    G.train_to_convergence(model, Xtrn, ytrn, Xval, yval, DEVICE)
                else:
                    train_adversarial(model, Xtrn, ytrn, Xval, yval, mask=None)
                model.eval()
                f1 = G.macro_f1(model, Xte, yte, DEVICE)
                clf = G._art_clf(model, Xtrn, DEVICE)
                for lv in EVAL_LEVELS:
                    for eps in EPS:
                        a = worst_case(model, clf, Xtrn, ytrn, Xval, yval, k,
                                       Xe, ye, eps, seed, masks[lv])
                        rows.append((defence, lv, DEPTH, act, k, seed, eps,
                                     round(a, 4), round(f1, 4)))
                        print(f"  {defence:8s} L{lv} {act:4s} s{seed} eps={eps}: "
                              f"worst-case ASR={a:.4f}  cleanF1={f1:.4f} "
                              f"({time.time()-t0:.0f}s)", flush=True)
                pd.DataFrame(rows, columns=["defence","level","depth","activation",
                                            "features","seed","eps","worst_asr",
                                            "clean_f1"]).to_csv(OUT_AT, index=False)

    d = pd.DataFrame(rows, columns=["defence","level","depth","activation","features",
                                    "seed","eps","worst_asr","clean_f1"])
    print(f"\nSaved {OUT_AT}")
    print("\n=== defence x threat model: worst-case ASR ===")
    print(d.groupby(["eps","level","defence"]).worst_asr.mean().unstack().round(3).to_string())
    print("\n=== cost of the defence: clean test macro-F1 ===")
    print(d.groupby(["activation","defence"]).clean_f1.mean().unstack().round(4).to_string())


if __name__ == "__main__":
    main()